steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'xrp-bot-v2'
      - '--source'
      - '.'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '1'
      - '--concurrency'
      - '80'
      - '--platform'
      - 'managed'
